name: 🐞 Bug report
description: If you found something that we should know about
labels: ["Bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: checkboxes
    attributes:
      label: Please answer the following questions for yourself before submitting an issue
      options:
        - label: Filters were updated before reproducing an issue
          required: true
        - label: I checked the [knowledge base](https://adguard.com/kb/) and found no answer
          required: true
        - label: I checked to make sure that this issue has not already been filed
          required: true

  - type: input
    id: app_version
    attributes:
      label: AdGuard version
      description: What version of our application are you running?
      placeholder: For example, 4.5.3
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment
      description: |
        Examples:
          - **OS**: 17
          - **Device**: iphone 15
      value: |
          - OS:
          - Device:
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        Select enabled filters if they are related to the application bug.
        If the issue is related to the filtering (missed ads, cookie, etc.)
        use the [Web Reporting Tool](https://kb.adguard.com/technical-support/reporting-tool) please.
        
  - type: dropdown
    id: filters_adblock
    attributes:
      label: Ad Blocking
      multiple: true
      options:
        - AdGuard Base filter
        - AdGuard Mobile Ads filter
        - EasyList
    validations:
      required: false

  - type: dropdown
    id: filters_privacy
    attributes:
      label: Privacy
      multiple: true
      options:
        - AdGuard Tracking Protection filter
        - EasyPrivacy
        - Peter Lowe's Blocklist
        - Fanboy's Anti-Facebook List
        - Fanboy's Anti-thirdparty Fonts
    validations:
      required: false

  - type: dropdown
    id: filters_social
    attributes:
      label: Social
      multiple: true
      options:
        - AdGuard Social Media filter
        - Fanboy's Social Blocking List
    validations:
      required: false

  - type: dropdown
    id: filters_annoyances
    attributes:
      label: Annoyances
      multiple: true
      options:
        - AdGuard Annoyances filter
        - AdGuard Cookie Notices filter
        - AdGuard Popups filter
        - AdGuard Mobile App Banners filter
        - AdGuard Other Annoyances filter
        - AdGuard Widgets filter
        - Adblock Warning Removal List
        - Fanboy's Annoyances
        - I don't care about cookies
        - EasyList Cookie List
        - Dandelion Sprout's Annoyances List
    validations:
      required: false

  - type: dropdown
    id: filters_security
    attributes:
      label: Security
      multiple: true
      options:
        - NoCoin Filter List
    validations:
      required: false

  - type: dropdown
    id: filters_other
    attributes:
      label: Other
      multiple: true
      options:
        - Filter unblocking search ads and self-promotion
        - AdGuard DNS filter
        - AdGuard Experimental filter
    validations:
      required: false

  - type: dropdown
    id: filters_regional
    attributes:
      label: Language-specific
      multiple: true
      options:
        - AdGuard Chinese filter
        - AdGuard Dutch filter
        - AdGuard French filter
        - AdGuard German filter
        - AdGuard Japanese filter
        - AdGuard Russian filter
        - AdGuard Spanish/Portuguese filter
        - AdGuard Turkish filter
        - AdGuard Ukrainian filter
        - ABPindo
        - ABPVN List
        - Adblock List for Finland
        - AdBlockID
        - Bulgarian list
        - CJX's Annoyances List
        - Dandelion Sprout's Nordic Filters
        - Dandelion Sprout's Serbo-Croatian List
        - EasyList China
        - EasyList Czech and Slovak
        - EasyList Dutch
        - EasyList Germany
        - EasyList Hebrew
        - EasyList Italy
        - EasyList Lithuania
        - EasyList Polish
        - EasyList Portuguese
        - EasyList Spanish
        - EasyList Thailand
        - Estonian List
        - Frellwit's Swedish Filter
        - Greek AdBlock Filter
        - Hungarian filter
        - Icelandic ABP List
        - IndianList
        - KAD - Anti-Scam
        - Latvian List
        - List-KR
        - Liste AR
        - Liste FR
        - Macedonian adBlock Filters
        - Official Polish filters for AdBlock, uBlock Origin & AdGuard
        - Persian Blocker
        - Polish Annoyances Filters
        - Polish Anti Adblock Filters
        - Polish Anti-Annoying Special Supplement
        - Polish GDPR-Cookies Filters
        - Polish Social Filters
        - road-block light
        - ROList
        - ROLIST2
        - RU AdList - Counters
        - Xfiles
        - xinggsf
        - YousList
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Advanced protection for Safari
      description: Do you have advanced protection enabled in AdGuard for iOS app?
      options:
        - label: yes, I do
    validations:
      required: false

  - type: dropdown
    id: dns_protection
    attributes:
      label: Which DNS server do you use?
      description: Skip this if DNS protection is disabled
      multiple: false
      options:
        - DNS protection disabled
        - System default
        - AdGuard DNS
        - AdGuard DNS Family Protection
        - AdGuard DNS Non-filtering
        - Google DNS
        - Cloudflare DNS
        - Cloudflare for Families - Malware and Adult Content
        - Cloudflare for Families - Malware Blocking
        - Open DNS
        - Open DNS with Family Shield
        - Quad9
        - Custom DNS
    validations:
      required: true
      
  - type: dropdown
    id: dns_protocol
    attributes:
      description: Skip this if DNS protection is disabled
      label: DNS protocol
      multiple: false
      options:
        - DNS protection disabled
        - Regular
        - DNSCrypt
        - DNS-over-HTTPS
        - DNS-over-TLS
        - DNS-over-QUIC
    validations:
      required: true
      
  - type: textarea
    id: custom_dns
    attributes:
      label: Custom DNS
      description: Please provide a link to the custom DNS you use
      placeholder: If you have enabled DNS from the pre-defined list, skip this step.
    validations:
      required: false

  - type: checkboxes
    id: dns_filter
    attributes:
      label: DNS filtering
      description: Do you have AdGuard DNS filter enabled?
      options:
        - label: yes, I do
          required: false

  - type: textarea
    id: custom_dns_filter
    attributes:
      label: Custom DNS filter
      description: Please provide a link to the custom DNS filter you use
      placeholder: Skip this step if you have DNS protection disabled.
    validations:
      required: false

  - type: dropdown
    id: dns_implementation
    attributes:
      label: DNS implementation
      description: Skip this if DNS protection is disabled
      multiple: false
      options:
        - DNS protection disabled
        - AdGuard
        - Native
    validations:
      required: true

  - type: dropdown
    id: tunnel_mode
    attributes:
      label: Tunnel mode
      description: Skip this if DNS protection is disabled
      multiple: false
      options:
        - DNS protection disabled
        - Split-Tunnel
        - Full-Tunnel
        - Full-Tunnel (without VPN icon)
    validations:
      required: true

  - type: textarea
    id: advanced
    attributes:
      label: Low-level settings
      description: Let us know if you have made any changes to the low-level settings
      placeholder: 
      value: |
        Bootstrap server:
        Fallback server:
        Blocking mode, etc:
    validations:
      required: false

  - type: textarea
    id: what-happened
    attributes:
      label: Issue Details
      description: Please provide a set of steps to reproduce the issue
      placeholder:
      value: |
        Steps to reproduce:
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: how_it_should_be
    attributes:
      label: Expected Behavior
      description:
      placeholder: A clear and concise description of what you expected to happen.
    validations:
      required: false
  
  - type: textarea
    id: how_it_is
    attributes:
      label: Actual Behavior
      placeholder: A clear description of what happened instead.
    validations:
      required: true

  - type: textarea
    id: screens
    attributes:
      label: Screenshots
      description: |
        If applicable add screenshots explaining your problem.
        You can drag and drop images or paste them from clipboard.
        Use `<details> </details>` tag to hide screenshots under the spoiler.
      placeholder: If applicable add screenshots explaining your problem.
      value: |
          <details><summary>Screenshot 1</summary>
          <!-- paste screenshot here -->
          </details>
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      placeholder: Add any other context about the problem here.
    validations:
      required: false